(define (problem extra1)
  (:domain rescue_drone)
  (:objects
    p1 p2 p3 p4 p5 p6 p7 p8 - person
    l1 l2 l3 l4 l5 l6 l7 l8 l9 l10 - location
)
  (:init
    (adjacent l1 l2)
    (adjacent l2 l3)
    (adjacent l3 l4)
    (adjacent l4 l5)
    (adjacent l5 l6)
    (adjacent l6 l7)
    (adjacent l7 l8)
    (adjacent l8 l9)
    (adjacent l9 l10)
    (drone-at l1)
    (safe-zone l10)
    (person-at p1 l2)
    (person-at p2 l3)
    (person-at p3 l4)
    (person-at p4 l5)
    (person-at p5 l6)
    (person-at p6 l7)
    (person-at p7 l8)
    (person-at p8 l9)
    (= (safe-zone-capacity) 6)
    (= (safe-zone-occupancy) 0)
  )
  (:goal (and
    (rescued p1)
    (rescued p2)
    (rescued p3)
    (rescued p4)
    (rescued p5)
    (rescued p6)
    (rescued p7)
    (rescued p8)
))
)
